ci: deprecate travis and move to github package (#11)
* remove travis config

* use sbt 1.5.1

* init github action

* move base jdk image to ghcr.io

* migrate ruby:2 to ghcr.io/meetup

* publish to ghcr.io

* refine workflow

Signed-off-by: Rui Chen <rui@chenrui.dev>

* rewrite build/publish steps

* `make publish` instead of `make publish-github-registry`

* fix non TTY device login issue

```
echo  | docker login ghcr.io -u meetcvs --password-stdin
Error: Cannot perform an interactive login from a non TTY device
make: *** [Makefile:9: _authenticate] Error 1
```

* use `ghcr.io` registry instead of github package registry